"use client";

import {useEffect,useState} from "react";

type Employee={id:number;registration:string;name:string;department:string;shift_name:string;face_status:string;status:string};
type Record={id:number;registration:string;name:string;event_type:string;occurred_at:string};

export default function Admin() {
  const [logged,setLogged]=useState(false), [email,setEmail]=useState(""), [password,setPassword]=useState("");
  const [tab,setTab]=useState("dashboard"), [employees,setEmployees]=useState<Employee[]>([]), [records,setRecords]=useState<Record[]>([]);
  const [name,setName]=useState(""),[registration,setRegistration]=useState(""),[department,setDepartment]=useState(""),[shift,setShift]=useState("1");
  const [file,setFile]=useState<File|null>(null),[notice,setNotice]=useState("");
  const [sound,setSound]=useState(true),[volume,setVolume]=useState(70);

  async function refresh(){const [e,r]=await Promise.all([fetch("/api/employees"),fetch("/api/attendance")]);setEmployees((await e.json()).employees||[]);setRecords((await r.json()).records||[]);}
  useEffect(()=>{fetch("/api/admin/me").then(r=>{if(r.ok){setLogged(true);refresh();}})},[]);

  async function login(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password})});if(r.ok){setLogged(true);setPassword("");refresh()}else setNotice("Login inválido.");}
  async function addEmployee(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/employees",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,registration,department,shiftId:Number(shift)})});const d=await r.json();setNotice(d.message||"Funcionário cadastrado.");if(r.ok){setName("");setRegistration("");setDepartment("");refresh();}}
  async function upload(){if(!file)return;const fd=new FormData();fd.append("file",file);const r=await fetch("/api/files",{method:"POST",body:fd});const d=await r.json();setNotice(d.message||"Arquivo enviado.");}
  if(!logged) return <main className="auth-page"><div className="login-card"><div className="brand"><div className="brand-mark">F</div><div><strong>FACECAN</strong><span>ADMINISTRAÇÃO</span></div></div><h1>Acesso administrativo</h1><p>Área protegida para RH, gestores e integração.</p><form onSubmit={login}><label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="admin@empresa.local" required/></label><label>Senha<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label><button className="primary-btn full">Entrar</button></form><small>{notice||"Defina ADMIN_EMAIL, ADMIN_PASSWORD e SESSION_SECRET no .env antes de produção."}</small><a href="/">← Voltar ao terminal</a></div></main>;

  const stats={employees:employees.length, records:records.length, pending:employees.filter(e=>e.face_status!=="ATIVO").length};
  return <main className="admin-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark">F</div><div><strong>FACECAN</strong><span>ADMIN V2</span></div></div><nav>
      {[
        ["dashboard","▦","Dashboard"],["employees","♙","Funcionários"],["records","◷","Registros"],["reports","▤","Relatórios"],["files","⇧","Central de arquivos"],["settings","⚙","Configurações"]
      ].map(([id,icon,label])=><button className={tab===id?"nav-active":""} key={id} onClick={()=>setTab(id)}><b>{icon}</b>{label}</button>)}
    </nav><a className="terminal-link" href="/">← Terminal de ponto</a></aside>
    <section className="admin-content"><header className="admin-header"><div><span className="eyebrow">GESTÃO CORPORATIVA</span><h1>{tab==="dashboard"?"Visão geral":tab==="employees"?"Funcionários":tab==="records"?"Registros":tab==="reports"?"Relatórios":tab==="files"?"Central de arquivos":"Configurações"}</h1></div><div className="header-user">● Administrador</div></header>
    {notice&&<div className="notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
    {tab==="dashboard"&&<><div className="stats"><div><span>FUNCIONÁRIOS</span><strong>{stats.employees}</strong><small>cadastrados</small></div><div><span>REGISTROS</span><strong>{stats.records}</strong><small>carregados</small></div><div><span>PENDÊNCIAS</span><strong>{stats.pending}</strong><small>biometrias</small></div><div><span>SEGURANÇA</span><strong>ATIVA</strong><small>auditoria habilitada</small></div></div><div className="panel"><div className="panel-title"><h2>Últimos registros</h2><button onClick={refresh}>Atualizar</button></div><RecordTable records={records.slice(0,10)}/></div></>}
    {tab==="employees"&&<div className="two-col"><div className="panel"><div className="panel-title"><h2>Novo funcionário</h2></div><form className="grid-form" onSubmit={addEmployee}><label>Matrícula<input value={registration} onChange={e=>setRegistration(e.target.value)} required/></label><label>Nome completo<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Departamento<input value={department} onChange={e=>setDepartment(e.target.value)}/></label><label>Turno<select value={shift} onChange={e=>setShift(e.target.value)}><option value="1">Manhã</option><option value="2">Noite</option></select></label><button className="primary-btn">Cadastrar funcionário</button></form></div><div className="panel"><div className="panel-title"><h2>Cadastro atual</h2></div><EmployeeTable employees={employees}/></div></div>}
    {tab==="records"&&<div className="panel"><div className="panel-title"><h2>Espelho de registros</h2><a className="outline-btn" href="/api/report?format=csv">Baixar CSV</a></div><RecordTable records={records}/></div>}
    {tab==="reports"&&<div className="report-grid"><a className="report-card" href="/api/report?format=pdf"><b>PDF</b><h2>Relatório de ponto</h2><span>Baixar relatório em PDF</span></a><a className="report-card" href="/api/report?format=csv"><b>CSV</b><h2>Exportação de registros</h2><span>Compatível com tratamento corporativo</span></a><div className="report-card"><b>ORACLE</b><h2>Layout de integração</h2><span>Preparado para exportação definida pela News Systems.</span></div></div>}
    {tab==="files"&&<div className="two-col"><div className="panel"><div className="panel-title"><h2>Enviar arquivo</h2></div><p>Arquivos ficam fora do diretório público e são registrados na auditoria.</p><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="primary-btn" onClick={upload}>Enviar para o servidor</button></div><div className="panel"><div className="panel-title"><h2>Integrações</h2></div><div className="integration"><b>AWS</b><span>Configuração por variáveis de ambiente</span></div><div className="integration"><b>News Systems</b><span>Endpoint/API a definir com o fornecedor</span></div><div className="integration"><b>Oracle</b><span>Exportação controlada e auditada</span></div></div></div>}
    {tab==="settings"&&<div className="panel settings"><div className="setting"><div><b>Som do terminal</b><span>Feedback sonoro após reconhecimento/registro</span></div><input type="checkbox" checked={sound} onChange={e=>setSound(e.target.checked)}/></div><div className="setting"><div><b>Volume</b><span>{volume}%</span></div><input type="range" min="0" max="100" value={volume} onChange={e=>setVolume(Number(e.target.value))}/></div><div className="setting"><div><b>Turno da manhã</b><span>Entrada 06–11 • intervalo 12–13:30 • saída 17–18</span></div><span className="pill">ATIVO</span></div><div className="setting"><div><b>Turno da noite</b><span>Entrada 18–22 • saída 01:20–07:00 • virada de dia</span></div><span className="pill">ATIVO</span></div><div className="security-box"><b>🔒 Segurança de produção</b><p>Use HTTPS, MFA, banco privado, backups, WAF, gestão de segredos, monitoramento e revisão independente antes de colocar o sistema em produção.</p></div></div>}
    </section>
  </main>;
}

function RecordTable({records}:{records:Record[]}){return <div className="table-wrap"><table><thead><tr><th>Funcionário</th><th>Matrícula</th><th>Evento</th><th>Data/hora</th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.registration}</td><td><span className="event">{r.event_type.replaceAll("_"," ")}</span></td><td>{new Date(r.occurred_at).toLocaleString("pt-BR")}</td></tr>)}{!records.length&&<tr><td colSpan={4}>Nenhum registro ainda.</td></tr>}</tbody></table></div>}
function EmployeeTable({employees}:{employees:Employee[]}){return <div className="table-wrap"><table><thead><tr><th>Funcionário</th><th>Matrícula</th><th>Turno</th><th>Biometria</th></tr></thead><tbody>{employees.map(e=><tr key={e.id}><td>{e.name}</td><td>{e.registration}</td><td>{e.shift_name}</td><td><span className="event">{e.face_status}</span></td></tr>)}</tbody></table></div>}
